-- table configuration
drop table configuration;
create table configuration (
  key text primary key,
  value jsonb
);
insert into configuration (key, value) values ('proc_map', null);

-- table todolist
drop table todolist;
create table todolist (
    id uuid primary key,
    user_id text,
    proc_inst_id text,
    proc_def_id text,
    activity_id text,
    start_date timestamp,
    end_date timestamp,
    status text,
    description text
);

-- table users
drop table public.users;
create table public.users (
    id uuid not null primary key,
    username text null,
    profile text null,
    email text null,
    is_admin boolean not null default false,
    notifications jsonb null
);
-- inserts a row into public.users
create or replace function public.handle_new_user() 
returns trigger as $$
begin
    insert into public.users (id, email)
    values (new.id, new.email);
      return new;
end;
$$ language plpgsql security definer;

-- trigger the function every time a user is created
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();


-- table organization
drop table organization;
create table organization (
  id bigint generated by default as identity,
  messages jsonb,
  organization_chart text
);

-- table proc_def
drop table proc_def;
create table proc_def (
  id text primary key,
  name text,
  definition jsonb,
  bpmn text
);

ALTER TABLE proc_def ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for authenticated users only" ON "public"."proc_def"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users.id = auth.uid()) AND (users.is_admin = true)))));

CREATE POLICY "Enable read access for all users" ON "public"."proc_def"
AS PERMISSIVE FOR SELECT
TO public
USING (true);


-- table proc_inst
drop table proc_inst;
create table proc_inst (
    id text primary key,
    user_ids text[],
    messages jsonb
);


create table public.chats (
    uuid text not null,
    id text not null,
    messages jsonb null,
    constraint chats_pkey primary key (uuid)
) tablespace pg_default;

create table public.calendar (
  uid text not null,
  data jsonb null,
  constraint calendar_pkey primary key (uid)
) tablespace pg_default;

create table public.chat_rooms (
  id text not null,
  participants jsonb not null,
  message jsonb null,
  name text null,
  constraint chat_rooms_pkey primary key (id)
) tablespace pg_default;

create table
  public.proc_def_arcv (
    arcv_id text not null,
    proc_def_id text not null,
    version double precision not null,
    snapshot text null,
    "timeStamp" timestamp without time zone null default current_timestamp,
    diff text null,
    constraint proc_def_arcv_pkey primary key (arcv_id)
  ) tablespace pg_default;

create table
  public.lock (
    id text not null,
    user_id text null,
    constraint lock_pkey primary key (id)
  ) tablespace pg_default;


-- 폼 UI 정보 저장을 위해서 사용되는 테이블
drop table if exists form_def;
create table form_def (
  id text primary key,
  name text not null,
  alias text not null,
  html text not null
) tablespace pg_default;