export interface Backend {
    listDefinition(basePath: string): Promise<any>;
    listVersionDefinitions(version: string, basePath: string): Promise<any>;
    listVersions(): Promise<any>;
    versionUp(version: string, major: boolean, makeProduction: boolean): Promise<any>;
    makeProduction(version: string): Promise<any>;
    getProduction(): Promise<any>;
    getDefinitionVersions(defId: string, options: any) : Promise<any>;
    getVersion(version: string): Promise<any>;
    getDefinition(defPath: string): Promise<any>;
    renameOrMove(definition: any, requestPath: string): Promise<any>;
    createFolder(newResource: any, requestPath: string): Promise<any>;
    deleteDefinition(requestPath: string, options: any): Promise<any>;
    restoreDefinition(defId: string, options: any): Promise<boolean | undefined>;
    getRawDefinition(defId: string, options: any): Promise<any>;
    putRawDefinition(definition: any, requestPath: string, options: any): Promise<any>;
    start(command: any): Promise<any>;
    stop(instanceId: string): Promise<any>;
    suspend(instanceId: string): Promise<any>;
    resume(instanceId: string): Promise<any>;
    getInstance(instanceId: string): Promise<any>;
    getAllInstanceList(page: any, size: any): Promise<any>;
    getInstanceListByGroup(group: string): Promise<any>;
    getFilteredInstanceList(filters: object, page: number, size: number): Promise<any>;
    backToHere(instanceId: string, tracingTag: string): Promise<any>;
    getProcessVariables(instanceId: string): Promise<any>;
    getVariable(instId: string, varName: string): Promise<any>;
    getVariableWithTaskId(instId: string, taskId: string, varName: string): Promise<any>;
    setVariable(instanceId: string, varName: string, varValue: any): Promise<any>;
    setVariableWithTaskId(instanceId: string, taskId: string, varName: string, varValue: any): Promise<any>;
    getRoleMapping(instId: string, roleName: string): Promise<any>;
    setRoleMapping(instanceId: string, roleName: string, roleMapping: any): Promise<any>;
    signal(instanceId: string, signal: string): Promise<any>;
    serviceMessage(requestPath: string): Promise<any>;
    getWorkItem(taskId: string): Promise<any>;
    putWorkItem(taskId: string, workItem: any): Promise<any>;
    putWorkItemComplete(taskId: string, workItem: any, isSimulate: string): Promise<any>;
    postMessage(instanceId: string, message: any): Promise<any>;
    fireMessage(instanceId: string, event: any): Promise<any>;
    getWorkList(options?: any): Promise<any>;
    getProcessDefinitionMap(): Promise<any>;
    putProcessDefinitionMap(definitionMap: any): Promise<any>;
    getPendingList(): Promise<any>;
    getCompletedList(options?: any): Promise<any>;
    getInProgressList(): Promise<any>;
    putWorklist(taskId: string, workItem: any): Promise<any>;
    getEventList(instanceId: string): Promise<any>;
    dryRun(isSimulate: string, command: object): Promise<any>;
    startAndComplete(command: object, isSimulate: string) : Promise<any>;
    getSystemList(): Promise<any>;
    putSystem(system: any): Promise<any>;
    deleteSystem(system: any): Promise<any>;
    getSystem(systemId: String): Promise<any>;
    getCurrentWorkItemByCorrKey(corrKey: number): Promise<any>;
    deleteInstance(instanceId: string): Promise<any>;
    setNotifications(value: any): Promise<any>;
    search(keyword: string): Promise<any>;
    testList(path: string): Promise<any>;
    testRecordList(path: string): Promise<any>;
    findCurrentWorkItemByInstId(instId: string): Promise<any>;
    getUserList(options: any): Promise<any>;
    getGroupList(): Promise<any>;
    releaseVersion(releaseName: string) : Promise<any>;
    uploadDefinition(file: File, path: string): Promise<any>;
    getCompletedTaskId(instId: string): Promise<any>;
    getActivitiesStatus(instId: string, executionScope: String): Promise<any>;
    deleteTest(path: string, tracingTag: string, index: number): Promise<any>;
    deleteRecordTest(path: string, index: number): Promise<any>;
    checkDBConnection(): Promise<any>;
    getWorkListAll(): Promise<any>;
    uploadImage(fileName: string, image: File): Promise<any>;
    getImageUrl(fileName: string): Promise<any>;
    uploadFile(fileName: string, file: File, storageType: string): Promise<any>;
    getFileUrl(path: string): Promise<any>;
    downloadFile(path: string): Promise<any>;
    getTenant(tenantId: string): Promise<any>;
    setTenant(tenantId: string): Promise<any>;
    updateUser(userInfo: any): Promise<any>;
    getAllWorkListByInstId(instId: number): Promise<any>;
    listMarketplaceDefinition(): Promise<any>;
    getRefForm(taskId: string): Promise<any>;
    saveTask(id: string, name: string, type: string, json: any): Promise<any>;
    getTaskList(): Promise<any>;
    watchNotifications(callback: (notification: any) => void): Promise<any>;
    getMCPTools(): Promise<any>;
    getMCPByTenant(): Promise<any>;
    setMCPByTenant(mcp: any): Promise<any>;
    getBSCard(): Promise<any>;
    putBSCard(card: any): Promise<any>;
    fetchAgentData(agentUrl: string): Promise<any>;
    getSchedule(id: string, version: string): Promise<any>;
    setSchedule(json: any): Promise<any>;
    deleteSchedule(defId: string, eventId: string): Promise<any>;
    getDataSourceList(): Promise<any>;
    addDataSource(dataSource: any): Promise<any>;
    updateDataSource(dataSource: any): Promise<any>;
    deleteDataSource(dataSource: any): Promise<any>;
    callDataSource(dataSource: any, bodyData: any): Promise<any>;
    getEnvByTenant(): Promise<any>;
    getSecretByTenant(): Promise<any>;
    deleteEnvByTenant(name: string): Promise<any>;
    deleteSecretByTenant(name: string): Promise<any>;
    createEnvByTenant(data: any): Promise<any>;
    createSecretByTenant(data: any): Promise<any>;
    updateEnvByTenant(data: any): Promise<any>;
    updateSecretByTenant(data: any): Promise<any>;
}

// export type { Backend }
