import { CLAUDE_DARK_THEME } from '@/ds/vuetify-bridge/theme';

/**
 * 다크 테마도 하나다. 자세한 설명은 `LightTheme.ts` 참고.
 */
const DARK_BLUE_THEME = { ...CLAUDE_DARK_THEME, name: 'DARK_BLUE_THEME' };
const DARK_AQUA_THEME = { ...CLAUDE_DARK_THEME, name: 'DARK_AQUA_THEME' };
const DARK_PURPLE_THEME = { ...CLAUDE_DARK_THEME, name: 'DARK_PURPLE_THEME' };
const DARK_GREEN_THEME = { ...CLAUDE_DARK_THEME, name: 'DARK_GREEN_THEME' };
const DARK_CYAN_THEME = { ...CLAUDE_DARK_THEME, name: 'DARK_CYAN_THEME' };
const DARK_ORANGE_THEME = { ...CLAUDE_DARK_THEME, name: 'DARK_ORANGE_THEME' };

export { DARK_BLUE_THEME, DARK_AQUA_THEME, DARK_ORANGE_THEME, DARK_PURPLE_THEME, DARK_GREEN_THEME, DARK_CYAN_THEME };
