apiVersion: apps/v1
kind: Deployment
metadata:
  name: completion-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: completion
  template:
    metadata:
      labels:
        app: completion
    spec:
      containers:
      - name: completion
        image: ghcr.io/uengine-oss/process-gpt-completion:3482b0e
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: OPENAI_API_KEY
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: SUPABASE_URL
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: SERVICE_ROLE_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: DB_PORT
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: LANGSMITH_API_KEY
        - name: LANGSMITH_PROJECT
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: LANGSMITH_PROJECT
---
apiVersion: v1
kind: Service
metadata:
  name: completion-service
spec:
  selector:
    app: completion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
