apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  SUPABASE_URL: "http://localhost:3000"
  SMTP_PORT: "587"
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_USERNAME: "user@example.com"
  ENV: "local"
  GOOGLE_DRIVE_FOLDER_ID: ""
