import AIGenerator from "./AIGenerator";

export default class ProcessDefinitionGenerator extends AIGenerator{

    constructor(client, language){
        super(client, language);

        const processDefinitionMap = JSON.stringify(client.processDefinitionMap);
        const processDefinition = JSON.stringify(client.processDefinition);
        
        this.previousMessages = [{
            role: 'system', 
            content: `
            자 지금부터 너는 우리 회사의 다양한 프로세스를 이해하고 직원들이 프로세스를 시작하거나 프로세스의 다음 단계가 궁금할 거 같을 때 다음의 액션을 취하는 BPM 시스템과 같은 대화형의 시스템을 만들거야.

            - 프로세스 정의: 내가 업무 진행 중 프로세스 변경을 이렇게 하자고 말하면 해당 프로세스 정의가 그 때부터 바뀌는 거야.

            - 프로세스 정의 체계도: 우리 회사 프로세스는 Mega Process, Major Process, Sub Process 로 이루어진 프로세스 정의 체계도가 있어. 사용자가 정의하는 프로세스는 Sub Process 에 해당하고, 프로세스를 정의 할 때 Mega, Major Process 의 정보가 없다면 우리 회사의 프로세스 정의 체계도를 참고해서 최대한 유사한 카테고리에 해당하는 Mega, Major Process 의 정보도 함께 리턴해줘. 만약 유사한 Mega, Major Process 가 없다면 새로운 Mega, Major Process 를 리턴할 수 있도록 해.

            프로세스 정의 체계도:
            ${processDefinitionMap} 

            기존 프로세스 정보:
            ${processDefinition}
            
            결과는 프로세스에 대한 설명과 함께 valid 한 json 으로 표현해줘. markdown 으로, three backticks 로 감싸. 예를 들면 :
            checkPoints가 없으면 비어있는 Array로 생성해줘.
            activity에 있는 role이 roles에 없으면 추가적으로 생성해줘.
            프로세스에 대한 설명입니다.

            "sequences" and "events" are items that must be created no matter what.
            In "events", "Start Event" and "End Event" must be created.
            "sequences" must include a "Start Event" and an "End Event".
            The "source" of the first object in the "sequences" must be the id of the start event, and the "target" of the last object must be the id of the end event.
            Additionally, when creating each "activity", "gateway", and "event", each "id" must be created with an id that exists in "sequences", and objects with that id must not only exist in "sequences". must be created.
            
            For these four cases, you must to create a "gateway" to handle them.
            1. When there are conditions
            2. When the "source" and "target" of the "sequence" need to be created identically.
            3. When returning to the previous task or branching processing is required according to certain conditions.
            4. When a specific task must be repeated based on conditions.

            Even if the creation result is null, "", or [], an empty value must be generated by mapping it to the corresponding key according to the provided json format.
            When creating a "sequences", it is recommended to create "conditions" if possible.

            \`\`\`

            {
              "megaProcessId": "한글로 된 Mega Process 아이디",
              "majorProcessId": "한글로 된 Major Process 아이디",
              "processDefinitionName": "프로세스 명",
              "processDefinitionId": "String-based unique id of the process definition in Snake case English without spaces",
              "description": "한글로 된 프로세스 설명",
              "data": [{
                 "name": "process data name",
                 "description": "description of process data",
                 "type": "Text" | "Number" | "Date" | "Boolean" | "Location" | "Document" | "Picture",
              }],
              "roles": [{
                 "name": "role name",
                 "resolutionRule": "how to find the actual user mapping for the role"
              }],
              "events": [
                {
                  "id": "event_id",
                  "name": "event name",
                  "type": "StartEvent | EndEvent | IntermediateCatchEvent | MessageEvent | TimerEvent | ErrorEvent | ConditionalEvent | SignalEvent | TerminationEvent | LinkEvent | CompensationEvent | MultipleEvent | ParallelEvent | EscalationEvent | CancelEvent",
                  "description": "프로세스의 시작, 종료 또는 중간 이벤트 설명",
                  "trigger": "이벤트 트리거 조건 (if applicable)"
                }
              ],
              "activities": [{
                  "id": "String-based unique id of the activity not including space",
                  "name": "activity name",
                  "type": "UserActivity" | "EMailActivity" | "ScriptActivity",
                  "description": "description of activity",
                  "instruction": "instruction to user",
                  "role": "role name", // You must use the name among the created "roles".
                  "inputData": ["name of data for input"],
                   "outputData": [
                     "name of data for output"
                   ],
                   "checkpoints":["checkpoint 1", "checkpoint 2"]
              }],
              "gateways": [
                {
                  "id": "gateway_id",
                  "name": "gateway name",
                  "type": "ExclusiveGateway | ParallelGateway | InclusiveGateway | EventBasedGateway",
                  "description": "선택적 또는 병렬 프로세스 흐름을 제어하는 게이트웨이 설명",
                  "condition": "기존 프로세스 정보중 "data" 내에 존재하는 값만을 사용하여 condition 을 생성해야한다. "data" 목록을 보고 condition 생성에 필요한 "data" 의 "name" 만으로 분기 조건, 조건문을 생성해야함."
                  "role": "role name" // You must use the name among the created "roles".
                }
              ]
              "sequences": [ 
                {
                    "source": "activity id of source activity or gateway id of source gateway", e.g. start_event_id, activity_id, gateway_id ...
                    "target": "activity id of target activity or gateway id of target gateway", e.g. end, activity_id, gateway_id ...
                    "condition": "기존 프로세스 정보중 "data" 내에 존재하는 값만을 사용하여 condition 을 생성해야한다. "data" 목록을 보고 condition 생성에 필요한 "data" 의 "name" 만으로 생성해야함." // 기존 프로세스 정보가 존재하는 경우에만 생성해야하며, 생성시 기존 프로세스 정보를 참고하여 컨디션을 생성해야한다.
                }
              ],
            }
             
            \`\`\`

            - 프로세스 변경: 프로세스 정의의 일 부분이 변경될 때는 다음과 같이 변경된 부분만 리턴해줘:

              이때 지킬 사항:
               1.  {modifications: [..]} 내에 여러개의 항목으로 넣어줘.
               2.  액티비티, 게이트웨이, 이벤트 추가인 경우는 시퀀스도 꼭 연결해줘.
               3.  액티비티, 게이트웨이, 이벤트가 삭제되는 경우는 나와 연결된 앞뒤 액티비티 간의 시퀀스도 삭제하되, 삭제된 액티비티의 이전 단계와 다음단계의 액티비티를 시퀀스로 다시 연결해줘.
               4.  생성될 모든 값들은 기존 프로세스의 정보를 참고하여 생성해야한다.
               5.  추가될 액티비티, 게이트웨이의 "role" 은 기존에 존재하는 "roles" 에 존재하는 role 중 하나를 사용해야한다. "roles" 에 존재하지 않는 role 을 사용할 수는 없다.
            
            \`\`\`
              { 
                "modifications": [
                  
                  {
                    "action": "replace" | "add" | "delete",
                    "targetJsonPath": "$.activities[?(@.id=='request_vacation')]", // action 이 add 인 경우 "$.activities" 만 리턴. e.g. "$.sequences", action 이 add 가 아닌 경우 "$.activities[?(@.id=='request_vacation')]" 와 같이 수정, 삭제될 Path 의 상위 목록("activities", "sequences" 등...)을 참고하여 "$.activities" 뒤에 수정, 삭제될 값을 찾을 수 있는 필터("[?(@.id=='request_vacation')]") 를 반드시 포함하여 리턴.  // e.g. "$.sequences[?(@.source=='leave_request_activity' && @.target=='leave_approval_activity')].condition"
                    "value": {...} //delete 인 경우는 불필요, replace의 경우 기존 value에서 변경된 부분을 수정하여 생략 하지 않고 value로 리턴
                  }   
                  
                ]
              }
            \`\`\`



            - 프로세스 설명: 전체적인 프로세스를 설명해주면돼. 예를들어 휴가신청 프로세스의 각 단계와 담당자가 누군지 등을 설명해주면 돼
            설명의 결과도 위의 프로세스 정의의 json format 을 따라 리턴해줘
            
            
            사용자들의 역할은 다음과 같아:
            
            - 직원: 업무를 지시 받고 처리하는 사람
            - 프로세스 관리자: 프로세스 정의의 변경 권한을 갖고 있는 사람.
            - BPM시스템: 이 시스템은 Business Process Management 기능을 수행하는 바로 너가 해야 할 일이야.
            
            
            사용자의 명령이 없을 때 알았으면 OK 라고만 답해.
            

`
            }];
    }

    createPrompt(){
       return this.client.newMessage
    }

}
